#Experiment 4: k-Nearest Neighbour Algorithm

Sonali Shripad Shanbhag 19BDS0114

**Aim: To implement k-Nearest Neighbour algorithm to classify the iris dataset and print both correct and wrong predictions. (Python ML library classes can be used for this problem)**

In [ ]:
from sklearn import datasets
import numpy as np
import random
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
iris = datasets.load_iris()
x = iris.data[:, 0:2]
y = iris.target

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)

#### kNN using in-built function from Sci-Kit Learn

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 8)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print("Accuracy: ")
print(100 * np.mean(y_pred == y_test), "%")

Accuracy: 
84.44444444444444 %


In [ ]:
print("RESULT\n", classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n",cm)

RESULT
               precision    recall  f1-score   support

           0       1.00      0.94      0.97        16
           1       0.62      0.91      0.74        11
           2       0.93      0.72      0.81        18

    accuracy                           0.84        45
   macro avg       0.85      0.86      0.84        45
weighted avg       0.88      0.84      0.85        45

Confusion Matrix: 
 [[15  1  0]
 [ 0 10  1]
 [ 0  5 13]]
